# Generated by Django 4.2.16 on 2026-05-18 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("streaming", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streamdonation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="streamsession",
            name="category",
            field=models.CharField(blank=True, default="Talk", max_length=50),
        ),
        migrations.AddField(
            model_name="streamsession",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="streamdonation",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="streamdonation",
            name="message",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="streamsession",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="streamsession",
            name="max_viewers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="streamsession",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="streams/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="streamviewer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="StreamSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(blank=True, default="Talk", max_length=50),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "streamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamClip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("clip_url", models.URLField(blank=True, default="")),
                ("start_time", models.FloatField(default=0)),
                ("end_time", models.FloatField(default=30)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="streaming.streamsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-views_count"],
            },
        ),
    ]
