# Generated by Django 4.2.16 on 2026-05-09 23:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeshMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_node_id", models.CharField(db_index=True, max_length=64)),
                ("encrypted_payload", models.BinaryField()),
                ("ttl", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeshNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=64, unique=True)),
                ("public_key", models.TextField()),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PeerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peer_node_id", models.CharField(max_length=64)),
                ("signal_strength", models.IntegerField(default=0)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="mesh.meshnode",
                    ),
                ),
            ],
        ),
    ]
