# Generated by Django 4.2.16 on 2026-05-09 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mesh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meshnode",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mesh_node",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meshmessage",
            name="relayed_by",
            field=models.ManyToManyField(
                related_name="relayed_messages", to="mesh.meshnode"
            ),
        ),
        migrations.AddField(
            model_name="meshmessage",
            name="sender_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="mesh.meshnode",
            ),
        ),
        migrations.AddIndex(
            model_name="meshmessage",
            index=models.Index(
                fields=["recipient_node_id", "-created_at"],
                name="mesh_meshme_recipie_8a36bc_idx",
            ),
        ),
    ]
