# Generated by Django 4.2.16 on 2026-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adcampaign",
            name="cpm",
            field=models.DecimalField(decimal_places=4, default=2.0, max_digits=6),
        ),
    ]
