# Generated by Django 4.2.16 on 2026-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0003_adcampaign_cpm"),
    ]

    operations = [
        migrations.AddField(
            model_name="adcampaign",
            name="target_age_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="target_age_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="target_gender",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="target_interests",
            field=models.JSONField(
                blank=True, default=list, help_text="List of interest tags"
            ),
        ),
    ]
