# Generated by Django 4.2.16 on 2026-05-18 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gigs", "0002_gig_completed_at_gig_dispute_reason_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gig",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="gigreview",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="skillbadge",
            options={"ordering": ["-endorsements"]},
        ),
        migrations.RemoveField(
            model_name="gig",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="gig",
            name="dispute_reason",
        ),
        migrations.RemoveField(
            model_name="gig",
            name="dispute_status",
        ),
        migrations.RemoveField(
            model_name="gig",
            name="milestones",
        ),
        migrations.AddField(
            model_name="gig",
            name="category",
            field=models.CharField(
                choices=[
                    ("design", "Design"),
                    ("development", "Development"),
                    ("writing", "Writing"),
                    ("marketing", "Marketing"),
                    ("video", "Video & Audio"),
                    ("music", "Music"),
                    ("business", "Business"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gig",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="gig",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gig",
            name="skills_required",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="gig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="skillbadge",
            name="earned_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gig",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gigs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="gig",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("disputed", "Disputed"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="taker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gigs_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gigreview",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="gigreview",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="gigreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=5
            ),
        ),
        migrations.AlterField(
            model_name="gigreview",
            name="reviewee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gigreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="portfolio/"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="skillbadge",
            name="endorsements",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="skillbadge",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="skillbadge",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gigreview",
            unique_together={("gig", "reviewer")},
        ),
        migrations.AlterUniqueTogether(
            name="skillbadge",
            unique_together={("user", "name")},
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="gigs.gig",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("resolution", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="gigs.gig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
