# Generated by Django 4.2.16 on 2026-05-16 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="badges/")),
                ("token_id", models.CharField(max_length=100, unique=True)),
                ("contract_address", models.CharField(max_length=100)),
                ("blockchain", models.CharField(default="ethereum", max_length=20)),
                ("verified", models.BooleanField(default=False)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-acquired_at"],
            },
        ),
    ]
