# Generated by Django 4.2.16 on 2026-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="frozen",
            field=models.BooleanField(default=False),
        ),
    ]
