# Generated by Django 4.2.16 on 2026-05-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_dailychallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
