# Generated by Django 4.2.16 on 2026-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_stripe_account_id_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers Only"),
                    ("private", "Only Me"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_balance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_earnings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_rank",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_transactions",
            field=models.BooleanField(default=False),
        ),
    ]
